"""Exact parametric TPMS (Gyroid, Schwarz P, Schwarz D) via the
Enneper-Weierstrass representation.

References
----------
* Gyroid:    P.J.F. Gandy, J. Klinowski, "Exact computation of the triply
  periodic G ('Gyroid') minimal surface", Chem. Phys. Lett. 321 (2000)
  363-371.  doi:10.1016/S0009-2614(00)00373-0
* Schwarz P: P.J.F. Gandy, J. Klinowski, "Exact computation of the triply
  periodic Schwarz P minimal surface", Chem. Phys. Lett. 322 (2000)
  579-586.  doi:10.1016/S0009-2614(00)00453-X
* Schwarz D: P.J.F. Gandy, D. Cvijovic, A.L. Mackay, J. Klinowski, "Exact
  computation of the triply periodic D ('diamond') minimal surface",
  Chem. Phys. Lett. 314 (1999) 543-551.  doi:10.1016/S0009-2614(99)01000-3

All three surfaces are Bonnet associates sharing the Weierstrass function

    R(tau) = 1 / sqrt(tau^8 - 14 tau^4 + 1)

with Bonnet angles theta_D = 0, theta_G = arccot(K'/K) = 38.0147740 deg,
theta_P = 90 deg, where K = K(m=1/4), K' = K(m=3/4) are complete elliptic
integrals (computed here by the AGM):

    r(omega) = Re[ e^{i theta} Int_0^omega (1-tau^2, i(1+tau^2), 2tau)
                                            R(tau) dtau ].

Every surface's fundamental curved triangles are paired across their circular
edges into genuine macro-quadrilateral patches. A shared cached cotangent-
harmonic square map removes the hidden diagonal's parameter kink. The Coons
evaluator below is retained only to resolve the published space-group copies.

The isometries assembling the fundamental patch into one cubic unit cell
were *derived numerically*, not copied from the papers (whose assembly
tables rest on internally inconsistent frame descriptions): the surface was
analytically continued across the three patch boundary curves, the
side-pairing isometries were extracted by Procrustes fits (residual ~1e-9),
the space group was generated by composition, and the cubic lattice was
read off from its pure translations. This reproduces the expected
crystallography exactly:

    Gyroid:    Ia-3d (No. 230),  96 triangles -> 48 macro quads, bcc
    Schwarz P: Im-3m (No. 229),  48 triangles -> 24 macro quads, bcc
    Schwarz D: Fd-3m (No. 227), 192 triangles -> 96 macro quads, fcc

The cubic lattice constants come out as exact elliptic-integral
expressions (verified against the integration to ~1e-9):

    L_P = K',    L_D = 2K,    L_G = 2KK' / sqrt(K^2 + K'^2)

(in kappa = 1 integration units). Rotation parts of all assembly
operations are signed permutation matrices; translations are multiples of
L/16; each operation carries an orientation sign (whether it swaps the two
sides of the surface -- for P and D this is NOT the determinant: their
symmetry groups contain in-surface 2-fold axes, proper yet side-swapping,
and surface-orthogonal mirrors, improper yet side-preserving). Every emitted mesh was verified: 100% quads, zero degenerate faces,
globally consistent orientation, all vertices on the exact minimal surface,
and exact periodicity -- on the 3-torus every edge borders exactly two
quads (no gaps, no overlaps), so Array-modifier tiles weld seamlessly.

Each cell is aligned with the standard level-set conventions (coordinates
in units of 2 pi / cell):

    Gyroid:    sin x cos y + sin y cos z + sin z cos x     (mean |F| ~ 0.007)
    Schwarz P: cos x + cos y + cos z                       (mean |F| ~ 0.045)
    Schwarz D: sin x sin y sin z + sin x cos y cos z
               + cos x sin y cos z + cos x cos y sin z     (mean |F| ~ 0.002)

This module is pure numpy (no bpy) and unit-tested outside Blender.
"""

import numpy as np
from collections import namedtuple

try:
    from . import bonnet_macro, gyroid_macro
except ImportError:  # Allow pure-Python validation from the repository root.
    import bonnet_macro
    import gyroid_macro

# ----------------------------------------------------------------------
# Constants
# ----------------------------------------------------------------------

def _ellipK(m):
    """Complete elliptic integral K(m) via the arithmetic-geometric mean."""
    a, b = 1.0, np.sqrt(1.0 - m)
    for _ in range(60):
        a, b = 0.5 * (a + b), np.sqrt(a * b)
        if abs(a - b) < 1e-16:
            break
    return np.pi / (2.0 * a)

_K14 = _ellipK(0.25)
_K34 = _ellipK(0.75)

_SQ2 = np.sqrt(2.0)
_C = 0.5 * _SQ2
_R0 = (np.sqrt(3.0) - 1.0) / _SQ2        # branch-point radius
_BP_P = _R0 + 0.0j
_BP_R = 1j * _R0
_ARC_C = -(1.0 + 1.0j) / _SQ2            # centre of the boundary arc
_Q_PT = _ARC_C + _SQ2 * np.exp(1j * np.pi / 4.0)

_GL_X, _GL_W = np.polynomial.legendre.leggauss(16)
_CORNER_EPS = 0.14

_Surface = namedtuple('_Surface', 'theta L_raw frame t_std ops')


# --- GYROID: Gandy & Klinowski, Chem. Phys. Lett. 321 (2000) 363-371 ---
_OPS_GYROID = (
    (1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1),
    (0, 0, 1, 0, -1, 0, -1, 0, 0, 4, 12, 4, 1),
    (0, 0, -1, 0, -1, 0, 1, 0, 0, 4, 12, 12, 1),
    (-1, 0, 0, 0, 0, 1, 0, 1, 0, 12, 4, 12, 1),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1, 8, 0, 0, 1),
    (0, 0, -1, -1, 0, 0, 0, -1, 0, 8, 8, 8, 1),
    (0, 0, 1, 1, 0, 0, 0, -1, 0, 8, 0, 8, 1),
    (0, 1, 0, 0, 0, -1, 1, 0, 0, 0, 8, 8, 1),
    (0, -1, 0, 0, 0, -1, -1, 0, 0, 8, 8, 8, 1),
    (1, 0, 0, 0, 0, -1, 0, 1, 0, 4, 4, 12, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, 1, 12, 4, 12, 1),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 12, 4, 4, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, -1, 12, 12, 12, 1),
    (0, 1, 0, -1, 0, 0, 0, 0, 1, 12, 12, 4, 1),
    (1, 0, 0, 0, 0, 1, 0, -1, 0, 12, 4, 4, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, -1, 12, 12, 4, 1),
    (0, 1, 0, -1, 0, 0, 0, 0, -1, 4, 12, 4, 1),
    (0, 1, 0, 0, 0, 1, -1, 0, 0, 0, 8, 0, 1),
    (0, -1, 0, 0, 0, 1, 1, 0, 0, 8, 8, 0, 1),
    (0, 0, 1, -1, 0, 0, 0, 1, 0, 0, 8, 8, 1),
    (0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1),
    (0, -1, 0, 0, 0, -1, 1, 0, 0, 0, 8, 0, 1),
    (0, 0, -1, 1, 0, 0, 0, 1, 0, 0, 0, 8, 1),
    (0, 1, 0, 0, 0, -1, -1, 0, 0, 0, 0, 8, 1),
    (0, -1, 0, 0, 0, 1, -1, 0, 0, 0, 8, 8, 1),
    (-1, 0, 0, 0, -1, 0, 0, 0, 1, 0, 8, 0, 1),
    (0, 0, -1, -1, 0, 0, 0, 1, 0, 8, 0, 8, 1),
    (0, 0, 1, -1, 0, 0, 0, -1, 0, 0, 0, 8, 1),
    (0, 0, -1, 1, 0, 0, 0, -1, 0, 8, 0, 0, 1),
    (0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1),
    (-1, 0, 0, 0, 0, -1, 0, -1, 0, 4, 4, 4, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, 1, 12, 4, 4, 1),
    (0, 1, 0, 1, 0, 0, 0, 0, 1, 4, 4, 4, 1),
    (0, 0, -1, 0, 1, 0, -1, 0, 0, 12, 12, 4, 1),
    (1, 0, 0, 0, 0, -1, 0, -1, 0, 4, 12, 4, 1),
    (-1, 0, 0, 0, 0, -1, 0, 1, 0, 4, 12, 12, 1),
    (1, 0, 0, 0, 0, 1, 0, 1, 0, 4, 4, 4, 1),
    (-1, 0, 0, 0, 0, 1, 0, -1, 0, 4, 4, 12, 1),
    (0, 0, 1, 0, 1, 0, 1, 0, 0, 12, 12, 12, 1),
    (-1, 0, 0, 0, 0, 1, 0, -1, 0, 12, 12, 4, 1),
    (1, 0, 0, 0, 0, 1, 0, 1, 0, 12, 12, 12, 1),
    (-1, 0, 0, 0, 0, -1, 0, 1, 0, 12, 4, 4, 1),
    (1, 0, 0, 0, 0, -1, 0, -1, 0, 12, 4, 12, 1),
    (0, 0, 1, 0, 1, 0, 1, 0, 0, 4, 4, 4, 1),
    (0, 0, -1, 0, 1, 0, -1, 0, 0, 4, 4, 12, 1),
    (0, 1, 0, 1, 0, 0, 0, 0, 1, 12, 12, 12, 1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0, 4, 12, 12, 1),
    (0, 0, -1, 0, -1, 0, -1, 0, 0, 12, 12, 12, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, 1, 4, 12, 12, 1),
    (0, 0, 1, 0, -1, 0, 1, 0, 0, 4, 4, 12, 1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0, 12, 4, 12, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, -1, 8, 8, 0, 1),
    (0, 0, 1, 1, 0, 0, 0, 1, 0, 8, 8, 8, 1),
    (0, 0, -1, 1, 0, 0, 0, -1, 0, 0, 8, 8, 1),
    (0, 0, 1, -1, 0, 0, 0, -1, 0, 8, 8, 0, 1),
    (0, 0, -1, -1, 0, 0, 0, 1, 0, 0, 8, 0, 1),
    (-1, 0, 0, 0, -1, 0, 0, 0, 1, 8, 0, 8, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 8, 1),
    (0, -1, 0, 0, 0, 1, -1, 0, 0, 8, 0, 0, 1),
    (-1, 0, 0, 0, -1, 0, 0, 0, -1, 8, 8, 8, 1),
    (1, 0, 0, 0, 1, 0, 0, 0, -1, 8, 0, 8, 1),
    (0, 1, 0, 0, 0, -1, -1, 0, 0, 8, 8, 0, 1),
    (-1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 8, 0, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, 1, 8, 0, 0, 1),
    (0, -1, 0, 0, 0, -1, 1, 0, 0, 8, 0, 8, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, 1, 0, 8, 8, 1),
    (-1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 8, 1),
    (0, 1, 0, 0, 0, 1, 1, 0, 0, 8, 8, 8, 1),
    (1, 0, 0, 0, 1, 0, 0, 0, -1, 0, 8, 0, 1),
    (-1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, 1),
    (0, 0, -1, 1, 0, 0, 0, 1, 0, 8, 8, 0, 1),
    (0, 0, 1, -1, 0, 0, 0, 1, 0, 8, 0, 0, 1),
    (0, -1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 8, 1),
    (0, 1, 0, 0, 0, 1, -1, 0, 0, 8, 0, 8, 1),
    (0, 1, 0, -1, 0, 0, 0, 0, -1, 12, 4, 12, 1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0, 4, 12, 4, 1),
    (0, 0, 1, 0, -1, 0, 1, 0, 0, 12, 12, 4, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, -1, 4, 4, 12, 1),
    (0, 0, -1, 0, -1, 0, -1, 0, 0, 4, 4, 4, 1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0, 12, 4, 4, 1),
    (1, 0, 0, 0, 0, 1, 0, -1, 0, 4, 12, 12, 1),
    (-1, 0, 0, 0, 0, -1, 0, -1, 0, 12, 12, 12, 1),
    (0, 1, 0, -1, 0, 0, 0, 0, 1, 4, 4, 12, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, -1, 4, 4, 4, 1),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 4, 12, 12, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, 1, 4, 12, 4, 1),
    (1, 0, 0, 0, 0, -1, 0, 1, 0, 12, 12, 4, 1),
    (0, -1, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 1),
    (0, 1, 0, 0, 0, -1, 1, 0, 0, 8, 0, 0, 1),
    (0, 0, 1, 1, 0, 0, 0, -1, 0, 0, 8, 0, 1),
    (0, 0, -1, -1, 0, 0, 0, -1, 0, 0, 0, 0, 1),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1, 0, 8, 8, 1),
    (-1, 0, 0, 0, 0, 1, 0, 1, 0, 4, 12, 4, 1),
    (0, 0, -1, 0, -1, 0, 1, 0, 0, 12, 4, 4, 1),
    (0, 0, 1, 0, -1, 0, -1, 0, 0, 12, 4, 12, 1),
    (1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 8, 8, 1),
)


# --- SCHWARZ_P: Gandy & Klinowski, Chem. Phys. Lett. 322 (2000) 579-586 ---
_OPS_SCHWARZ_P = (
    (1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, -1, 8, 8, 8, -1),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 8, 8, 8, -1),
    (0, 0, 1, 0, -1, 0, 1, 0, 0, 0, 0, 0, 1),
    (-1, 0, 0, 0, -1, 0, 0, 0, 1, 0, 0, 0, 1),
    (0, 0, -1, 1, 0, 0, 0, -1, 0, 8, 8, 8, -1),
    (0, 0, -1, -1, 0, 0, 0, 1, 0, 8, 8, 8, -1),
    (0, 1, 0, 0, 0, -1, -1, 0, 0, 8, 8, 8, -1),
    (0, -1, 0, 0, 0, 1, -1, 0, 0, 8, 8, 8, -1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0, 0, 0, 0, 1),
    (-1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1),
    (1, 0, 0, 0, 0, -1, 0, 1, 0, 0, 0, 0, 1),
    (1, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 1),
    (-1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, 1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1),
    (-1, 0, 0, 0, 0, 1, 0, 1, 0, 8, 8, 8, -1),
    (-1, 0, 0, 0, 0, -1, 0, -1, 0, 8, 8, 8, -1),
    (0, -1, 0, 0, 0, -1, 1, 0, 0, 8, 8, 8, -1),
    (0, 1, 0, 0, 0, 1, 1, 0, 0, 8, 8, 8, -1),
    (0, 0, 1, -1, 0, 0, 0, -1, 0, 8, 8, 8, -1),
    (0, 1, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 1),
    (0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1),
    (0, 0, 1, 1, 0, 0, 0, 1, 0, 8, 8, 8, -1),
    (0, -1, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 1),
    (0, -1, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, 1),
    (0, 0, -1, 1, 0, 0, 0, -1, 0, 0, 0, 0, 1),
    (0, 0, 1, -1, 0, 0, 0, -1, 0, 0, 0, 0, 1),
    (0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1),
    (0, 0, -1, -1, 0, 0, 0, 1, 0, 0, 0, 0, 1),
    (0, 0, -1, 0, -1, 0, -1, 0, 0, 0, 0, 0, 1),
    (1, 0, 0, 0, 0, 1, 0, -1, 0, 8, 8, 8, -1),
    (1, 0, 0, 0, 0, -1, 0, 1, 0, 8, 8, 8, -1),
    (0, -1, 0, 1, 0, 0, 0, 0, 1, 8, 8, 8, -1),
    (0, 0, 1, 0, -1, 0, 1, 0, 0, 8, 8, 8, -1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0, 8, 8, 8, -1),
    (0, 0, -1, 0, -1, 0, -1, 0, 0, 8, 8, 8, -1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0, 8, 8, 8, -1),
    (0, 1, 0, -1, 0, 0, 0, 0, 1, 8, 8, 8, -1),
    (0, -1, 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1),
    (0, 1, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 1),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 1),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 1),
    (1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 8, 8, -1),
    (1, 0, 0, 0, -1, 0, 0, 0, -1, 8, 8, 8, -1),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1, 8, 8, 8, -1),
    (-1, 0, 0, 0, -1, 0, 0, 0, 1, 8, 8, 8, -1),
)


# --- SCHWARZ_D: Gandy, Cvijovic, Mackay & Klinowski, Chem. Phys. Lett. 314 (1999) 543-551 ---
_OPS_SCHWARZ_D = (
    (1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, -1),
    (0, 0, -1, 0, 1, 0, -1, 0, 0, 12, 0, 12, 1),
    (0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, -1, 8, 8, 8, -1),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1, 12, 0, 12, -1),
    (0, -1, 0, 0, 0, 1, 1, 0, 0, 8, 12, 12, 1),
    (0, -1, 0, 0, 0, -1, -1, 0, 0, 8, 8, 8, 1),
    (0, 0, 1, -1, 0, 0, 0, 1, 0, 4, 8, 4, 1),
    (0, 0, -1, -1, 0, 0, 0, -1, 0, 8, 8, 8, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, 1, 8, 12, 12, -1),
    (-1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 12, 4, -1),
    (1, 0, 0, 0, 0, 1, 0, -1, 0, 12, 12, 8, -1),
    (1, 0, 0, 0, 0, -1, 0, 1, 0, 4, 8, 4, -1),
    (-1, 0, 0, 0, 0, -1, 0, -1, 0, 8, 8, 8, -1),
    (0, 1, 0, -1, 0, 0, 0, 0, 1, 4, 8, 4, -1),
    (1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 4, 4, 1),
    (1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1),
    (0, 0, -1, 1, 0, 0, 0, 1, 0, 0, 12, 4, 1),
    (0, 0, 1, 1, 0, 0, 0, -1, 0, 12, 12, 8, 1),
    (0, 1, 0, 0, 0, 1, -1, 0, 0, 4, 12, 0, 1),
    (0, 0, -1, 1, 0, 0, 0, -1, 0, 12, 8, 4, -1),
    (0, 0, -1, -1, 0, 0, 0, 1, 0, 12, 12, 0, -1),
    (0, 1, 0, 0, 0, -1, 1, 0, 0, 4, 8, 4, 1),
    (0, 0, 1, -1, 0, 0, 0, -1, 0, 0, 4, 4, -1),
    (0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, -1),
    (1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 4, 4, -1),
    (0, 1, 0, 0, 0, -1, -1, 0, 0, 8, 4, 12, -1),
    (0, -1, 0, 0, 0, -1, 1, 0, 0, 4, 4, 0, -1),
    (0, -1, 0, 0, 0, 1, -1, 0, 0, 12, 0, 12, -1),
    (0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, -1),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 4, 12, 0, -1),
    (-1, 0, 0, 0, 0, 1, 0, -1, 0, 12, 8, 4, 1),
    (-1, 0, 0, 0, 0, -1, 0, 1, 0, 12, 12, 0, 1),
    (0, 0, -1, 0, -1, 0, 1, 0, 0, 12, 4, 8, 1),
    (0, 1, 0, 1, 0, 0, 0, 0, 1, 8, 8, 0, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, -1, 4, 8, 12, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, 1, 12, 12, 0, 1),
    (0, 1, 0, -1, 0, 0, 0, 0, -1, 0, 12, 12, 1),
    (0, 0, 1, 0, -1, 0, -1, 0, 0, 0, 4, 4, 1),
    (0, 1, 0, -1, 0, 0, 0, 0, -1, 8, 4, 12, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, 1, 4, 4, 0, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, -1, 12, 0, 12, 1),
    (0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1),
    (0, 0, 1, 0, -1, 0, -1, 0, 0, 8, 4, 12, 1),
    (0, 0, -1, 0, -1, 0, 1, 0, 0, 4, 4, 0, 1),
    (-1, 0, 0, 0, 0, -1, 0, 1, 0, 12, 4, 8, 1),
    (0, 0, 1, 0, -1, 0, 1, 0, 0, 4, 0, 12, -1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0, 4, 4, 8, -1),
    (-1, 0, 0, 0, 0, 1, 0, -1, 0, 12, 0, 12, 1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0, 8, 12, 12, -1),
    (0, 0, -1, 0, -1, 0, -1, 0, 0, 8, 8, 8, -1),
    (-1, 0, 0, 0, -1, 0, 0, 0, 1, 12, 4, 8, -1),
    (0, 1, 0, 0, 0, 1, 1, 0, 0, 8, 8, 0, -1),
    (0, -1, 0, 0, 0, 1, -1, 0, 0, 4, 8, 12, -1),
    (0, -1, 0, 0, 0, -1, 1, 0, 0, 12, 12, 0, -1),
    (0, 1, 0, 0, 0, -1, -1, 0, 0, 0, 12, 12, -1),
    (-1, 0, 0, 0, -1, 0, 0, 0, 1, 4, 4, 0, -1),
    (1, 0, 0, 0, -1, 0, 0, 0, -1, 8, 4, 12, -1),
    (0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 8, 8, -1),
    (-1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 8, 1),
    (-1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 4, 12, 1),
    (0, 0, 1, -1, 0, 0, 0, -1, 0, 0, 12, 12, -1),
    (1, 0, 0, 0, 1, 0, 0, 0, -1, 12, 12, 8, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, 1, 12, 8, 12, 1),
    (0, 0, -1, -1, 0, 0, 0, 1, 0, 12, 4, 8, -1),
    (1, 0, 0, 0, -1, 0, 0, 0, 1, 4, 0, 12, 1),
    (1, 0, 0, 0, 1, 0, 0, 0, -1, 4, 4, 8, 1),
    (0, 0, -1, 1, 0, 0, 0, -1, 0, 12, 0, 12, -1),
    (-1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 12, 12, 1),
    (-1, 0, 0, 0, -1, 0, 0, 0, -1, 8, 8, 8, 1),
    (0, 1, 0, 0, 0, -1, 1, 0, 0, 4, 0, 12, 1),
    (0, 1, 0, 0, 0, 1, -1, 0, 0, 4, 4, 8, 1),
    (0, 0, 1, 1, 0, 0, 0, -1, 0, 4, 12, 0, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, 1, 12, 0, 4, 1),
    (-1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 4, 1),
    (0, 0, -1, 1, 0, 0, 0, 1, 0, 8, 12, 12, 1),
    (-1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 12, 4, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, 1, 4, 8, 4, 1),
    (1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 8, 8, 1),
    (0, 0, -1, 0, -1, 0, -1, 0, 0, 0, 0, 8, -1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0, 0, 4, 12, -1),
    (1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 12, 12, 1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0, 12, 12, 8, -1),
    (0, 0, 1, 0, -1, 0, 1, 0, 0, 12, 8, 12, -1),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 4, 4, 8, -1),
    (0, 1, 0, -1, 0, 0, 0, 0, 1, 4, 0, 12, -1),
    (-1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 8, 0, -1),
    (0, 0, -1, 0, -1, 0, -1, 0, 0, 8, 0, 0, -1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0, 12, 4, 0, -1),
    (1, 0, 0, 0, 0, -1, 0, 1, 0, 12, 8, 12, -1),
    (0, 0, 1, 0, 1, 0, -1, 0, 0, 4, 12, 0, -1),
    (0, 0, -1, 0, -1, 0, -1, 0, 0, 0, 8, 0, -1),
    (1, 0, 0, 0, 0, 1, 0, -1, 0, 4, 12, 0, -1),
    (0, 0, 1, 0, -1, 0, 1, 0, 0, 12, 0, 4, -1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0, 8, 4, 4, -1),
    (-1, 0, 0, 0, 0, 1, 0, 1, 0, 8, 12, 12, -1),
    (0, 0, -1, 0, 1, 0, 1, 0, 0, 0, 12, 4, -1),
    (0, 0, 1, 0, -1, 0, 1, 0, 0, 4, 8, 4, -1),
    (-1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 8, -1),
    (1, 0, 0, 0, 0, -1, 0, 1, 0, 12, 0, 4, -1),
    (1, 0, 0, 0, 0, 1, 0, -1, 0, 4, 4, 8, -1),
    (-1, 0, 0, 0, 0, 1, 0, 1, 0, 8, 4, 4, -1),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 12, 12, 8, -1),
    (0, -1, 0, 1, 0, 0, 0, 0, 1, 0, 12, 4, -1),
    (0, 1, 0, -1, 0, 0, 0, 0, -1, 8, 12, 4, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, -1, 4, 0, 4, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, -1, 12, 8, 4, 1),
    (0, 1, 0, -1, 0, 0, 0, 0, -1, 0, 4, 4, 1),
    (0, 0, -1, -1, 0, 0, 0, -1, 0, 0, 8, 0, 1),
    (-1, 0, 0, 0, -1, 0, 0, 0, -1, 8, 0, 0, 1),
    (1, 0, 0, 0, 1, 0, 0, 0, -1, 12, 4, 0, 1),
    (0, 0, 1, -1, 0, 0, 0, 1, 0, 12, 8, 12, 1),
    (1, 0, 0, 0, 1, 0, 0, 0, -1, 4, 12, 0, 1),
    (-1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 8, 0, 1),
    (0, 0, 1, 1, 0, 0, 0, -1, 0, 4, 4, 8, 1),
    (0, 0, -1, 1, 0, 0, 0, 1, 0, 8, 4, 4, 1),
    (0, 0, -1, -1, 0, 0, 0, -1, 0, 0, 0, 8, 1),
    (0, 0, 1, -1, 0, 0, 0, 1, 0, 12, 0, 4, 1),
    (0, 1, 0, 0, 0, -1, 1, 0, 0, 12, 8, 12, 1),
    (0, -1, 0, 0, 0, -1, -1, 0, 0, 0, 8, 0, 1),
    (0, 1, 0, 0, 0, 1, 1, 0, 0, 8, 0, 8, -1),
    (0, -1, 0, 0, 0, -1, 1, 0, 0, 4, 12, 8, -1),
    (0, -1, 0, 0, 0, -1, 1, 0, 0, 12, 4, 8, -1),
    (0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 8, 8, -1),
    (0, 1, 0, 0, 0, 1, -1, 0, 0, 12, 12, 8, 1),
    (0, -1, 0, 0, 0, 1, 1, 0, 0, 0, 12, 4, 1),
    (0, 1, 0, 0, 0, -1, -1, 0, 0, 8, 12, 4, -1),
    (0, -1, 0, 0, 0, 1, -1, 0, 0, 4, 0, 4, -1),
    (0, -1, 0, 0, 0, 1, -1, 0, 0, 12, 8, 4, -1),
    (0, 1, 0, 0, 0, -1, -1, 0, 0, 0, 4, 4, -1),
    (0, -1, 0, 0, 0, -1, -1, 0, 0, 8, 0, 0, 1),
    (0, 0, 1, 1, 0, 0, 0, 1, 0, 8, 8, 0, -1),
    (0, 0, 1, -1, 0, 0, 0, -1, 0, 8, 12, 4, -1),
    (0, -1, 0, 0, 0, 1, 1, 0, 0, 8, 4, 4, 1),
    (0, 0, -1, -1, 0, 0, 0, 1, 0, 4, 4, 0, -1),
    (0, 0, -1, 1, 0, 0, 0, -1, 0, 4, 0, 4, -1),
    (-1, 0, 0, 0, -1, 0, 0, 0, 1, 12, 12, 0, -1),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1, 12, 8, 4, -1),
    (0, 0, -1, -1, 0, 0, 0, 1, 0, 4, 12, 8, -1),
    (0, 0, 1, 1, 0, 0, 0, 1, 0, 8, 0, 8, -1),
    (0, 0, -1, 1, 0, 0, 0, -1, 0, 4, 8, 12, -1),
    (0, 0, 1, -1, 0, 0, 0, -1, 0, 8, 4, 12, -1),
    (0, 1, 0, -1, 0, 0, 0, 0, 1, 12, 8, 12, -1),
    (0, -1, 0, -1, 0, 0, 0, 0, -1, 0, 8, 0, -1),
    (0, 1, 0, 1, 0, 0, 0, 0, 1, 8, 0, 8, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, 1, 4, 12, 8, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, 1, 12, 4, 8, 1),
    (0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 8, 8, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, 1, 8, 4, 4, -1),
    (-1, 0, 0, 0, 0, -1, 0, 1, 0, 4, 4, 0, 1),
    (-1, 0, 0, 0, 0, 1, 0, -1, 0, 4, 0, 4, 1),
    (0, -1, 0, -1, 0, 0, 0, 0, -1, 8, 0, 0, -1),
    (1, 0, 0, 0, 0, 1, 0, 1, 0, 8, 8, 0, 1),
    (1, 0, 0, 0, 0, -1, 0, -1, 0, 8, 12, 4, 1),
    (0, 0, 1, 0, -1, 0, -1, 0, 0, 0, 12, 12, 1),
    (0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 8, 8, 1),
    (1, 0, 0, 0, 0, 1, 0, 1, 0, 8, 0, 8, 1),
    (-1, 0, 0, 0, 0, -1, 0, 1, 0, 4, 12, 8, 1),
    (1, 0, 0, 0, 0, -1, 0, -1, 0, 8, 4, 12, 1),
    (-1, 0, 0, 0, 0, 1, 0, -1, 0, 4, 8, 12, 1),
    (0, 0, -1, 0, -1, 0, 1, 0, 0, 12, 12, 0, 1),
    (0, 0, -1, 0, 1, 0, -1, 0, 0, 12, 8, 4, 1),
    (0, 0, 1, 0, 1, 0, 1, 0, 0, 8, 0, 8, 1),
    (0, 0, -1, 0, 1, 0, -1, 0, 0, 4, 0, 4, 1),
    (0, 0, 1, 0, 1, 0, 1, 0, 0, 8, 8, 0, 1),
    (0, 0, -1, 0, 1, 0, -1, 0, 0, 4, 8, 12, 1),
    (1, 0, 0, 0, 0, 1, 0, -1, 0, 12, 4, 0, -1),
    (-1, 0, 0, 0, 0, -1, 0, -1, 0, 8, 0, 0, -1),
    (-1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 4, 12, -1),
    (1, 0, 0, 0, 0, -1, 0, 1, 0, 4, 0, 12, -1),
    (1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 12, 12, -1),
    (1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 8, 8, -1),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1, 4, 0, 4, -1),
    (1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 0, 8, -1),
    (-1, 0, 0, 0, 1, 0, 0, 0, -1, 4, 8, 12, -1),
    (1, 0, 0, 0, 1, 0, 0, 0, 1, 8, 8, 0, -1),
    (0, 0, -1, -1, 0, 0, 0, -1, 0, 8, 0, 0, 1),
    (0, 0, 1, 1, 0, 0, 0, -1, 0, 12, 4, 0, 1),
    (0, 0, 1, -1, 0, 0, 0, 1, 0, 4, 0, 12, 1),
    (0, 0, -1, 1, 0, 0, 0, 1, 0, 0, 4, 12, 1),
    (0, -1, 0, 0, 0, -1, -1, 0, 0, 0, 0, 8, 1),
    (0, -1, 0, 0, 0, 1, 1, 0, 0, 0, 4, 12, 1),
    (0, 1, 0, 0, 0, 1, -1, 0, 0, 12, 4, 0, 1),
    (0, 1, 0, 0, 0, -1, 1, 0, 0, 12, 0, 4, 1),
    (0, -1, 0, 1, 0, 0, 0, 0, 1, 0, 4, 12, -1),
    (0, -1, 0, -1, 0, 0, 0, 0, -1, 0, 0, 8, -1),
    (0, 1, 0, -1, 0, 0, 0, 0, 1, 12, 0, 4, -1),
    (0, 1, 0, 1, 0, 0, 0, 0, -1, 12, 4, 0, -1),
    (0, 0, -1, 0, -1, 0, 1, 0, 0, 4, 12, 8, 1),
    (0, 0, 1, 0, -1, 0, -1, 0, 0, 8, 12, 4, 1),
    (1, 0, 0, 0, -1, 0, 0, 0, -1, 8, 12, 4, -1),
    (-1, 0, 0, 0, -1, 0, 0, 0, 1, 4, 12, 8, -1),
)



SURFACES = {
    'GYROID': _Surface(
        theta=np.arctan(_K14 / _K34),
        L_raw=2.0 * _K14 * _K34 / np.hypot(_K14, _K34),
        frame=np.array(((_C, -_C, 0.0),
               (0.0, 0.0, 1.0),
               (-_C, -_C, 0.0))),
        t_std=np.array([12, 14, 8]) / 16.0,
        ops=_OPS_GYROID,
    ),
    'SCHWARZ_P': _Surface(
        theta=0.5 * np.pi,
        L_raw=_K34,
        frame=np.array(((-_C, -_C, 0.0),
               (-_C, _C, 0.0),
               (0.0, 0.0, 1.0))),
        t_std=np.array([8, 0, 12]) / 16.0,
        ops=_OPS_SCHWARZ_P,
    ),
    'SCHWARZ_D': _Surface(
        theta=0.0,
        L_raw=2.0 * _K14,
        frame=np.array(((_C, _C, 0.0),
               (0.0, 0.0, 1.0),
               (-_C, _C, 0.0))),
        t_std=np.array([14, 10, 14]) / 16.0,
        ops=_OPS_SCHWARZ_D,
    ),
}

# ----------------------------------------------------------------------
# Fundamental patch
# ----------------------------------------------------------------------

def _coons(u, v):
    """Map the unit square onto the curved-quad parameter domain O-P-Q-R."""
    bottom = u * _BP_P
    top = _ARC_C + _SQ2 * np.exp(1j * (np.pi / 3.0 - u * np.pi / 12.0))
    left = v * _BP_R
    right = _ARC_C + _SQ2 * np.exp(1j * (np.pi / 6.0 + v * np.pi / 12.0))
    return ((1 - v) * bottom + v * top + (1 - u) * left + u * right
            - (u * (1 - v) * _BP_P + u * v * _Q_PT + (1 - u) * v * _BP_R))

def _integrand(t):
    """(1 - t^2, i(1 + t^2), 2t) * R(t), stacked on the last axis."""
    t4 = t ** 4
    rw = 1.0 / np.sqrt(t4 * t4 - 14.0 * t4 + 1.0)
    return np.stack([(1.0 - t * t) * rw,
                     1j * (1.0 + t * t) * rw,
                     2.0 * t * rw], axis=-1)

def _segment_integrals(A, B):
    """Gauss-Legendre integrals of the Weierstrass form along straight
    segments A->B. Segments ending near a branch point are integrated in
    the zeta = sqrt(tau - branch) chart, where the integrand is analytic."""
    A = np.asarray(A, dtype=complex)
    B = np.asarray(B, dtype=complex)
    out = np.zeros(A.shape + (3,), dtype=complex)

    dP = np.minimum(abs(A - _BP_P), abs(B - _BP_P))
    dR = np.minimum(abs(A - _BP_R), abs(B - _BP_R))
    near_p = (dP < _CORNER_EPS) & (dP <= dR)
    near_r = (dR < _CORNER_EPS) & (dR < dP)
    plain = ~(near_p | near_r)

    if plain.any():
        a, b = A[plain], B[plain]
        mid = 0.5 * (a + b)[:, None]
        half = 0.5 * (b - a)[:, None]
        vals = _integrand(mid + half * _GL_X[None, :])
        out[plain] = np.einsum('sgk,g->sk', vals, _GL_W) * half

    for mask, bp in ((near_p, _BP_P), (near_r, _BP_R)):
        if not mask.any():
            continue
        a, b = A[mask], B[mask]
        za, zb = np.sqrt(a - bp), np.sqrt(b - bp)
        flip = (za.real * zb.real + za.imag * zb.imag) < 0.0
        zb = np.where(flip, -zb, zb)
        mid = 0.5 * (za + zb)[:, None]
        half = 0.5 * (zb - za)[:, None]
        zn = mid + half * _GL_X[None, :]
        vals = _integrand(bp + zn * zn) * (2.0 * zn)[..., None]
        out[mask] = np.einsum('sgk,g->sk', vals, _GL_W) * half
    return out

def _fundamental_patch(surf, res):
    """Integrate the Enneper-Weierstrass representation on an
    (res+1) x (res+1) grid. Returns (points, normals) in the standard
    cubic frame with unit cell edge 1."""
    u = np.linspace(0.0, 1.0, res + 1)
    U, V = np.meshgrid(u, u, indexing='ij')
    om = _coons(U, V)

    phi = np.zeros((res + 1, res + 1, 3), dtype=complex)
    segs = _segment_integrals(om[:-1, 0], om[1:, 0])
    phi[1:, 0] = np.cumsum(segs, axis=0)
    segs = _segment_integrals(om[:, :-1].ravel(), om[:, 1:].ravel())
    phi[:, 1:] = phi[:, :1] + np.cumsum(segs.reshape(res + 1, res, 3), axis=1)

    xyz = (np.exp(1j * surf.theta) * phi).real       # raw frame, kappa = 1

    # Gauss map: the unit normal is the inverse stereographic image of omega.
    gauss = np.stack([2.0 * om.real, 2.0 * om.imag, np.abs(om) ** 2 - 1.0],
                     axis=-1)
    gauss /= np.linalg.norm(gauss, axis=-1, keepdims=True)

    det = float(np.linalg.det(surf.frame))
    return (xyz @ surf.frame.T / surf.L_raw + surf.t_std,
            gauss @ surf.frame.T * det)

# ----------------------------------------------------------------------
# Unit-cell assembly
# ----------------------------------------------------------------------

def build_unit_cell(tpms_type='GYROID', cell_size=1.0, res=2,
                    solver_resolution=44, quadrature_order=200):
    """Build one cubic unit cell of an exact TPMS as an all-quad mesh.

    Parameters
    ----------
    tpms_type : str   -- key into SURFACES ('GYROID', 'SCHWARZ_P',
                         'SCHWARZ_D').
    cell_size : float -- world edge length of the cubic translational cell.
    res       : int   -- quads per macro-patch edge. G/P/D have
                         48/24/96 * res^2 genuine macro quads.

    Returns
    -------
    verts   : (V, 3) float64 -- welded vertices, cell spans ~[0, cell_size]^3
    quads   : (Q, 4) int32   -- quad faces, globally consistent orientation
    normals : (V, 3) float64 -- smooth unit normals
    """
    if tpms_type == 'GYROID':
        return gyroid_macro.build_unit_cell(
            cell_size=cell_size,
            quad_subdivisions=res,
            solver_resolution=solver_resolution,
            quadrature_order=quadrature_order,
        )

    surf = SURFACES[tpms_type]
    if tpms_type in {'SCHWARZ_P', 'SCHWARZ_D'}:
        reference_patch, _ = _fundamental_patch(surf, 2)
        return bonnet_macro.build_unit_cell(
            surface_name=tpms_type,
            surface=surf,
            reference_patch=reference_patch,
            cell_size=cell_size,
            quad_subdivisions=res,
            solver_resolution=solver_resolution,
            quadrature_order=quadrature_order,
        )

    res = max(2, int(res))
    patch, pnorm = _fundamental_patch(surf, res)
    npts = (res + 1) * (res + 1)

    idx = np.arange(npts).reshape(res + 1, res + 1)
    q0 = np.stack([idx[:-1, :-1].ravel(), idx[1:, :-1].ravel(),
                   idx[1:, 1:].ravel(), idx[:-1, 1:].ravel()], axis=1)

    pflat = patch.reshape(-1, 3)
    nflat = pnorm.reshape(-1, 3)
    nops = len(surf.ops)
    all_v = np.empty((nops * npts, 3))
    all_n = np.empty((nops * npts, 3))
    all_q = np.empty((nops * res * res, 4), dtype=np.int64)

    q0r = q0[:, ::-1]                        # reversed winding
    for k, row in enumerate(surf.ops):
        M = np.array(row[:9], dtype=float).reshape(3, 3)
        t = np.array(row[9:12], dtype=float) / 16.0
        sign = float(row[12])                # +1 keeps sides, -1 swaps
        p = pflat @ M.T + t
        t -= np.floor(p.mean(axis=0))        # keep the copy near [0, 1)^3
        det = float(np.linalg.det(M))
        all_v[k * npts:(k + 1) * npts] = pflat @ M.T + t
        all_n[k * npts:(k + 1) * npts] = nflat @ M.T * (sign * det)
        all_q[k * res * res:(k + 1) * res * res] =             (q0 if sign > 0 else q0r) + k * npts

    # weld: vertices from different patches on shared boundary curves agree
    # to ~1e-9, far below the smallest quad size (~0.1 / res).
    tol = 1e-6
    keys = np.round(all_v / tol).astype(np.int64)
    _, first, inverse = np.unique(keys, axis=0, return_index=True,
                                  return_inverse=True)
    verts = all_v[first] * cell_size
    normals = all_n[first]
    quads = inverse[all_q].astype(np.int32)
    return verts, quads, normals
